### ISSUE TITLE
Integrate Provider with RBAC server

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/provider#152]

**Comment by alexcos20** [comment]
In order to allow more fine grained permissions, provider has to use the RBAC server to allow/deny some actions.

This is done by posting a message (based on action type) to the RBAC server, and decide if that action can continue or shall be rejected.

Provider will accept RBAC_SERVER_URL env. If that ENV is not defined, then the provider is not going to use any RBAC server.

The list of messages / based on action is:

Provider: encryptUrl
It wil be triggered by provider when a user is trying to encrypt a URL
Format:
```
{​ 
 "eventType": "encryptUrl", 
"component": "provider" , 
"providerAddress:"0x123",
"signature":"0x1234",
"credentials": {
              	"type": address,
              	"address": "0x123"
     	}
}
```
where signature = sign(eventType+credentials) using the provider private key


Provider: initialize
It wil be triggered by provider when a user is initializing an order
Format:
```
{​ 
 "eventType": "initialize", 
"component": "provider" , 
"providerAddress:"0x123",
"signature":"0x1234",
"credentials": {
              	"type": address,
              	"address": "0x123"
     	},
	“dids:{
[
			“did”:”0x123”,
			“serviceId”:”1”
		]
	}
}
```
where signature = sign(eventType+credentials) using the provider private key

Provider: access
It wil be triggered by provider when a user is trying to consume an access service
Format:
```
{​ 
 "eventType": "access", 
"component": "provider" , 
"providerAddress:"0x123",
"signature":"0x1234",
"credentials": {
              	"type": address,
              	"address": "0x123"
     	}
	“dids:{
[
			“did”:”0x123”,
			“serviceId”:”1”
		]
	}
}
```
where signature = sign(eventType+credentials) using the provider private key
 
 
Provider: compute
It wil be triggered by provider when a user is trying to start a compute job
Format:
```
{​ 
 "eventType": "compute", 
"component": "provider" , 
"providerAddress:"0x123",
"signature":"0x1234",
"credentials": {
              	"type": address,
              	"address": "0x123"
     	}
	“dids:{
[
			“did”:”0x123”,
			“serviceId”:”1”
		]
	},
“algos:{
[
			“did”:”0x123”,
			“serviceId”:”1”
		]
	},
“additionalDids:{
[
			“did”:”0x123”,
			“serviceId”:”1”
		],
[
			“did”:”0x124”,
			“serviceId”:”1”
		]
	}
}
```
where signature = sign(eventType+credentials+dids+algos+additionalDids) using the provider private key

**Comment by calina-c** [comment]
cc: @alexcos20, @jamiehewitt15 From my POV, this is a downgrade from the current flow. If the RBAC server will only return True/False and no detail about *why* the action is not permitted, then the end users will be confused. Are there any conventions to the RBAC answer? e.g. format for the answer?

What is the logic if no RBAC_SERVER_URL? Do we fallback on the previous provider logic? So we keep that, but only if there is no RBAC server?

for @mariacarmina we can start working on the request decorators an only employ them if no RBAC server exists. We'll have to upgrade the tests too. For now, let's assume the RBAC server simply returns "true" or "false" and we'll adapt once we have a sample of the response.

**Comment by jamiehewitt15** [comment]
> cc: @alexcos20, @jamiehewitt15 From my POV, this is a downgrade from the current flow. If the RBAC server will only return True/False and no detail about _why_ the action is not permitted, then the end users will be confused. Are there any conventions to the RBAC answer? e.g. format for the answer?

The format of the response is a regular HTTP response. If you get a 200 response and `false` then there is only one possible reason: the user does not have the required role (publisher, consumer etc). If it is not a 200 response then the problem can be interpreted from the error code. 
 
> What is the logic if no RBAC_SERVER_URL? Do we fallback on the previous provider logic? So we keep that, but only if there is no RBAC server?

If there is no `RBAC_SERVER_URL` the logic should be entirely unchanged from before. This is the same way we have implemented it in the market.

**Comment by jamiehewitt15** [comment]
Also, I'm not sure if it was obvious before but this is a feature that will only be used by our enterprise clients. The users will have been introduced to the fact that they only have permissions for certain actions. For our own use case (in Ocean Market) the `RBAC_SERVER_URL` will be left blank

**Comment by alexcos20** [comment]
RBAC is just another AND validation.

If you don't have RBAC_SERVER_URL defined, you are following the current validation flow.
If you have RBAC_SERVER_URL defined, you are following the current validation flow + check RBAC. If both are passing, then the request is good to go. If one of them is failing, the request is denied
