### ISSUE TITLE
Integration of IDS International Data Spaces Connector by Fraunhofer

### ISSUE THREAD

**Issue by kaimeinke** [oceanprotocol/provider#87]
**Is your feature request related to a problem? Please describe.**
German research institutes, industry and some data markets already use the IDS, developed by Fraunhofer, for P2P data sharing. It could be worth pursuing integration into the Ocean Provider to tap into existing infrastructure and research in this field to make it easier for other German players to adopt Ocean Compute-to-Data.

https://www.dataspaces.fraunhofer.de/en/software/connector.html 

IDS offers a Dataspace Connector, Enterprise Integration Connector, Open Data Connector and a trusted Connector, some of these are open source solutions.

One marketplace is know of is https://www.advaneo-datamarketplace.de/en/# 

This is more of an early idea, I am not yet able to grasp if this is truly useful, but a lot of German players are going to follow the IDS approach as I heard.

**Comment by alexcos20** [comment]
thanks, I will take a look

**Comment by kaimeinke** [comment]
Hi @trentmc and @alexcos20 , I had a meeting today with the head of marketing at IDSA and they proposed building a use case and a meeting with the CTO of IDSA. IDSA is well on the way to making a standard in the Gaia-X space, given the massive industry support, so we are happy to discuss this during the next weeks as another service that could work well with compute-to-data and data monetization.

**Comment by kaimeinke** [comment]
In further discussion with the IDSA team a big loophole and two areas for potential cooperation has been identified.

IDS connectors actually transfer the data and currently got no means of pricing. At the same time the whole ecosystem relies on a trusted environment (not trustless) as members of the dataspace have to stick to a rule book which can only in part be technically enforced.

1. Trusted connector:
"Trust" is achieved through a set of policies that allow remote deletion of transferred data. This can be done in case somebody leaves the space (all copied data in IDS infrastructure will be deleted via self-destruct) or given time contstraints (self-destruct) and this works only if data is not copied outside the IDS connector on the consumers side.

See "Usage Control": https://industrial-data-space.github.io/trusted-connector-documentation/docs/usage_control/ 

![image](https://user-images.githubusercontent.com/59994024/114686651-499e9080-9d13-11eb-8813-edcb506b05b6.png)
![image](https://user-images.githubusercontent.com/59994024/114686696-54592580-9d13-11eb-8ea1-b48b4a564654.png)

It is clear that moving the data is the core problem here and Ocean got that covered by Compute-to-Data.

No need to discuss the GDPR risks etc. associated with it as we all discussed that a lot.

2. Pricing & Quality Signals

Current implementations such as the Telekom market show the problem of missing market-price information. Markets will be crowded with low quality data right from the start. 

https://portal.dih.telekom.net/marketplace 

Just keeping this updated as I see a lot of room for a fruitful cooperation in the future.

**Comment by trentmc** [comment]
Thanks for the updates, Kai. This is great news.

It seems there are these possible places to put IDS: 
1. as a particular Ocean Provider "static url" service. Won't solve copying of data, but works otherwise. 
2. as a particular Ocean Provider "Compute to Data" service. Solves copying of data, helps enforce other policies.
3. as a _new_ Ocean Provider service, side-by-side with "static url" and "Compute to Data". Doesn't feel like it needs to be this one, but we should keep the door open to this, just in case it needs it.

Any of the above (1)(2)(3) can be combined with other Ocean functionality permissions: 
- **basic datatoken functionality:** you can only consume the data if you redeem 1.0 datatokens to the provider
- **restrict consume:** restrict who can actually consume the data, via an RBAC server. "You can only access if you have 1.0 datatokens _and_ appropriate credentials." Super flexible. [multi repo 76](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/multi-repo-issue/76)
- **encrypt metadata:** allow a 3rd party market to restrict others from seeing metadata -- [react 264](https://app.zenhub.com/workspaces/ocean-main-5e5e5a97e91ce03f380fb9b7/issues/oceanprotocol/react/264)
- **filter assets:** 3rd party market only shows data assets published on it -- goes with the above

**Comment by kaimeinke** [comment]
I just had a look and discussion with the Telekom Team regarding their marketplace and approach to prices and usage statistics, Ocean is miles away with flexible prices and transparent usage information. This combined with the Ocean functionality permissions make Ocean Protocol the perfect add on for all those markets. Amazing day and good to see how early we are regarding IDS and Gaia-X and how great the product to market fit of Ocean Protocol is. Incredible.
